### PR TITLE
Handle duplicated Messages + Fix MarkAsSeen

### LINKED ISSUE #215: Handle duplicated Messages

### LINKED ISSUE #216: Fix MarkAsSeen with duplicated Messages

### PR DESCRIPTION
**Pull request by KevinBoulongne**
Closes #215
Closes #216

Depends on #204

### CODE REVIEW

File: app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt [hunk 1]
```diff
@@ -117,6 +118,36 @@ object ThreadController {
...
+        if (thread.unseenMessagesCount != 0) {
+
+            RealmController.mailboxContent.writeBlocking {
+                val latestThread = getLatestThreadSync(thread.uid) ?: return@writeBlocking
+
+                var nbUnseenMessages = 0
+                val uids = mutableListOf<String>().apply {
+                    latestThread.messages.forEach {
+                        if (!it.seen) {
+                            nbUnseenMessages++
```
Comment (FabianDevel) [inline app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt:131]:
```suggestion
                            // nbUnseenMessages++
```

File: app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt [hunk 2]
```diff
@@ -117,6 +118,36 @@ object ThreadController {
         } ?: false
     }
 
+    fun markAsSeen(thread: Thread) {
+        if (thread.unseenMessagesCount != 0) {
+
+            RealmController.mailboxContent.writeBlocking {
+                val latestThread = getLatestThreadSync(thread.uid) ?: return@writeBlocking
+
+                var nbUnseenMessages = 0
```
Comment (FabianDevel) [inline app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt:127]:
```suggestion
                // var nbUnseenMessages = 0
```

**Review by LunarX — APPROVED** [review]

**Review by JorisBodin — APPROVED** [review]
